#!/bin/bash

#SBATCH -p main

#SBATCH --mem=1024
#SBATCH --job-name=030tests17w1000
#SBATCH --output=s17_w1000_30test.out

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=30
#SBATCH --nodes=3

#SBATCH --time=0:30:00

module load slurm 

module load gromacs/openmpi/gcc/64/4.5.4 

STARTTIME=$(date +%s)

#use sleep or testing... 

cd /scratch/eixeres/s17_w1000/

tpbconv -s NVT_sam17_water1000_next.tpr  -until 50 -o NVT_sam17_water1000_next_next.tpr 

mpirun -np 30 mdrun -s NVT_sam17_water1000_next_next.tpr -cpi  NVT_sam17_water1000_next.cpt -maxh 0.5

#cp -r /scratch/eixeres/s17_w1000/ /home/eixeres/simulations/finished/
