#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=79s33_w400079
#SBATCH --output=s33_w4000.out

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=16
#SBATCH --nodes=2

#SBATCH --time=24:00:00

module load slurm 

module load gromacs/single/openmpi1.4.5/4.6.5

STARTTIME=$(date +%s)

#use sleep or testing... 

cd /scratch/eixeres/s33_w4000

mpirun -np 16 mdrun -s NVT_sam33_water4000.tpr -deffnm  NVT_sam33_water4000 -maxh 24

mkdir /home/eixeres/finished/
cp -r /scratch/eixeres/s33_w4000 /home/eixeres/finished/
