#!/bin/bash
#SBATCH --job-name=ii_quiero_k150
#SBATCH --mail-type=end
#SBATCH --mem=2048
#SBATCH --time=48:00:00
#SBATCH --mail-user=laila@physik.fu-berlin.de
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8

grompp -f production.mdp -n index.ndx -p A10-B10-sol.top -c trjconv225.gro -o topol.tpr -maxwarn 1

mdrun -nt 8 -s topol.tpr -o traj -x traj -e ener -g md -px -pf -maxh 48

sbatch jobscript_continue